version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install mlflow boto3
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 851725217119.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mlflow-tracking-server .
      - docker tag mlflow-tracking-server:latest 851725217119.dkr.ecr.us-west-2.amazonaws.com/mlflow-tracking-server:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 851725217119.dkr.ecr.us-west-2.amazonaws.com/mlflow-tracking-server:latest
artifacts:
  files:
    - '**/*'
