version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mlflow-tracking-server .
      - docker tag mlflow-tracking-server:latest 851725217119.dkr.ecr.us-east-1.amazonaws.com/mlflow-tracking-server:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 851725217119.dkr.ecr.us-east-1.amazonaws.com/mlflow-tracking-server:latest
artifacts:
  files:
    - '**/*'
