version: 0.2

phases:
  pre_build:
    commands:
      - nohup /usr/local/bin/dockerd-entrypoint.sh &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install boto3 mlflow
  build:
    commands:
      - python deployment_script.py
